### ISSUE TITLE
i taked this fault.

### ISSUE THREAD

**Issue by orcuncun** [sdkbox/sdkbox-sample-ccc200#1]
Simulator: E/jswrapper (271): ERROR: Uncaught ReferenceError: sdkbox is not defined, location: assets/Script/HelloWorld.js:0:0

**Comment by yinjimmy** [comment]
which branch?

**Comment by orcuncun** [comment]
I solved the problem.
But I'm having problems in the other (SDKBOX Ads ). The ad is not showing.
I just tried the admob. Should I also try other advertising companies for Sdbox?

**Comment by orcuncun** [comment]
When I use "sdkbox ads", I need to import "admob" and other ad add-ons?

**Comment by orcuncun** [comment]
i can show ads with codes.
 const adName = 'interstitial'; //interstitial ad
        // const adName = 'reward'; //reward video
        if (sdkbox.PluginAdMob.isAvailable(adName)) {
            sdkbox.PluginAdMob.show(adName);
        } else {
            this.log(adName + ' is not available');
            sdkbox.PluginAdMob.cache(adName);
        }
But i cant show ads with codes.
 onButton1: function() {
        const placement = 'placement-1';
        if (sdkbox.PluginSdkboxAds.isAvailable(placement)) {
            sdkbox.PluginSdkboxAds.placement(placement);
        } else {
            this.log(placement + ' is not available');
        }
    },

    onButton2: function() {
        sdkbox.PluginSdkboxAds.playAd("AdMob", "interstitial");
        //sdkbox.PluginSdkboxAds.playAd("UnityAds", "rewardedVideo");
    },
Can you explain the difference
What should I do to use the 2nd part?
Admob ads were not displayed when using Chapter 2.

**Comment by orcuncun** [comment]
i solved this problem. But i taked this fault.
this placement is not available.
