### ISSUE TITLE
I installed and run all plugins.

### ISSUE THREAD

**Issue by orcuncun** [sdkbox/sdkbox-sample-ccc200#2]
application crashes

**Comment by yinjimmy** [comment]
whats logcat message?

**Comment by orcuncun** [comment]
After waiting a few seconds the app crashes on your Android device. I'm thinking of removing individual ad settings from the sdkbox config.json file.

**Comment by orcuncun** [comment]
i solved my problem but unity ads haven't video finish control. that property worked for other ads ( admob,chartboost etc.)
i used this code,
sdkbox.PluginSdkboxAds.setListener({
            onAdAction : function(ad_unit_id, zone_location_place_you_name_it, action_type) {
                self.log("Aktif olanlar:" + String(ad_unit_id) + ":" + String(zone_location_place_you_name_it) + ":" + String(action_type));
            },
            onRewardAction : function(ad_unit_id, zone_id, reward_amount, reward_succeed) {
                self.log("Video watched:" + String(ad_unit_id) + ":" + String(zone_id) + ":" + String(reward_amount) + ":" + String(reward_succeed));
                self.log2(ad_unit_id);
            }
        });

**Comment by orcuncun** [comment]
How do I uninstall an add-on I want to delete? example: unity_ads
